import type { Metadata } from "next";
import { Roboto, Outfit } from "next/font/google";

import "./globals.css";
import "@fontsource/outfit";
import "@fontsource/roboto";
import { cn } from "@/lib/utils";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin", "cyrillic"]
});

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "CV",
  description: "Generated by create next app"
};

export const viewport = {
  width: "device-width",
  initialScale: 1,
};


export default function RootLayout(
  { children }: 
  { 
    children: React.ReactNode;
  }
) {

  return (
    <html className={
      cn(
        "h-full",
        "antialiased",
        //roboto.variable
      )
    }>
      <body className="h-full flex flex-col items-center px-[24px]">
        {children}
      </body>
    </html>
  );
}