name: Deploy CV

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /var/www/cv
            git config --global --add safe.directory /var/www/cv
            git fetch origin
            git reset --hard origin/master
            /root/.bun/bin/bun install
            rm -rf .next
            /root/.bun/bin/bun run build
            sudo systemctl restart cv